### ISSUE TITLE
你好，这个后面会支持支持图生图，垫图这个功能吗？

### ISSUE THREAD

**Issue by itxtl** [barretlee/chatgpt-text-to-midjourney-image#2]
你好，这个后面会支持支持图生图，垫图这个功能吗？

**Comment by barretlee** [comment]
有没有发现，整个交互流程其实挺简单的，就是把几个 API 连起来串一下，你可以试一试，再找一个能够理解图的大模型，将图片转换成文本，然后继续沿用本项目的代码，生成更多图片。

本项目更像是一个 demo，玩一玩的水平，没有打算做的很强大。
